name: docker-registry-api
definition: src
generators:
  - name: fernapi/fern-java
    version: 0.0.76
    generate: true
    config:
      packagePrefix: com
      mode: client
  - name: fernapi/fern-postman
    version: 0.0.14
    generate:
      enabled: true
      output: ./generated-postman.json
